### ISSUE TITLE
[EngAut] RFCs Web Page

### ISSUE THREAD

**Issue by mordamax** [paritytech/eng-automation#1]
@PierreBesson suggested rendering our polkadot-fellows/RFCs as a webpage - similar to https://eips.ethereum.org/

Could be made by markdown book https://rust-lang.github.io/mdBook/index.html
Must be integrated into RFC's repo https://github.com/polkadot-fellows/RFCs/

**Comment by rzadp** [comment]
Hey, I've done some initial work on this. cc @paritytech/opstooling 

I created a separate repo: https://github.com/paritytech/rfc-book

Here is the current output: https://paritytech.github.io/rfc-book/

### How it works

It downloads the contents of the RFCs repo (approved RFCs), downloads the contents of all pending PRs (proposed RFCs), and constructs an mdbook out of it.
The book is published to gh-pages.

It's not finished but I'm sending it here for preview early. Important thing I know it's missing is a link to source (e.g. looking at a proposed RFCs, I would want to have a link to the PR it comes from in case I want to make a comment there).

### My questions

> Must be integrated into RFC's repo

Does it really need to be integrated into that repo, or could it be a separate repo in `polkadot-fellows`?

For one, I wouldn't want to mix ugly bash PRs with RFC text PRs.
Second, (if I'm right) we won't rely on commits on `main`, but we will do the cron-based updates (because we can't feasibly track all the commits on all the PRs, which also come from forks) - so we don't have to hook into events from that repo.

**Comment by rzadp** [comment]
A new preview is available [here](https://paritytech-stg.github.io/RFCs/).

The updated code can be reviewed [here](https://github.com/paritytech/RFCs/pull/1)

**Comment by mordamax** [comment]
Closes with https://github.com/polkadot-fellows/RFCs/pull/60
